{% set name = "grunnur" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grunnur-{{ version }}.tar.gz
  sha256: b76182b7045e67d9eb7e0902e39d9cc6940dc3221aa3d1c168007183dc01ce89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pdm-pep517
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22
    - mako >=1

test:
  imports:
    - grunnur
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Uniform API for PyOpenCL and PyCUDA.
  home: https://github.com/fjarri/grunnur
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
